### ISSUE TITLE
app crashes when an already existing todo is edited

### ISSUE THREAD

**Issue by jalaj711** [jalaj711/todox-v1#2]
**Describe the bug**
when you try to edit an already existing todo and then click on the edit button, make some changes and click on the save button, the app will crash with an error.

**Expected behavior**
the todo should be updated correctly

**Comment by Jaivrat12** [comment]
Hey @jalaj711!
Can you please assign me this issue?

**Comment by racky7** [comment]
Hi, @jalaj711 can you assign it to me? I have worked on this kind of issue.

**Comment by jalaj711** [comment]
Since we have two requests on this one, I am assigning this to @Jaivrat12 as he seems to have commented first. Sorry @racky7, maybe you can try out some other issue...
