### ISSUE TITLE
Updating a todo item adds it as a new todo item

### ISSUE THREAD

**Issue by Jaivrat12** [jalaj711/todox-v1#9]
**Describe the bug**
After editing a to-do item, the changes are added as a new one, and the item that you originally edited stays in its old state.

**To Reproduce**
1. Edit a todo item (create one if there're none and then edit it)
2. Make some changes if you want
3. Click the `SAVE` button
4. You'll see that a new item has been added with the changes that you made

**Expected behavior**
Changes made should be applied to the one being edited, instead of creating a new one.

**Comment by Jaivrat12** [comment]
Hi @jalaj711,
I found this bug and raised this issue!
Can you please apply appropriate labels (like `bug`, `hacktoberfest`, etc.) and assign this to me?
I'd like to solve this issue!

Thanks

**Comment by jalaj711** [comment]
Sure.
